{{-- resources/views/banks/partials/_create-complaint-form.blade.php --}}

@php
    /*
    |--------------------------------------------------------------------------
    | Customer options
    |--------------------------------------------------------------------------
    |
    | We keep using the existing $clients variable.
    | No controller/database changes are required.
    |
    | The JavaScript below reads both the option text and value,
    | so customers can be searched by name OR customer code/ID.
    |
    */

    $clientOptions = collect($clients ?? []);
@endphp


<x-modal
    id="complaintModal"
    title="تسجيل شكوى جديدة"
    width="46rem"
>

    <form
        id="newComplaintForm"
        method="POST"
        action="{{ route('banks.complaints.store', $bank->id) }}"
        class="space-y-4"
        autocomplete="off"
    >

        @csrf


        {{-- ============================================================
             CUSTOMER SECTION
             ============================================================ --}}

        <div class="rounded-xl border border-info/20 bg-info/[0.025] p-4">

            {{-- Section header --}}
            <div class="mb-4 flex items-start justify-between gap-3">

                <div class="flex items-start gap-3">

                    <div class="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl border border-info/20 bg-info/10 text-info">
                        <i class="fa-solid fa-user text-sm"></i>
                    </div>

                    <div>

                        <h3 class="text-sm font-bold text-fg">
                            بيانات العميل
                        </h3>

                        <p class="mt-1 text-[10px] leading-5 text-dim">
                            ابحث باسم العميل أو كود / رقم العميل ثم اختره من النتائج.
                        </p>

                    </div>

                </div>

                <span class="badge badge-info">
                    مطلوب
                </span>

            </div>


            {{-- ========================================================
                 CUSTOMER SEARCH
                 ======================================================== --}}

            <div class="relative">

                <label
                    for="complaintClientSearch"
                    class="mb-1.5 block text-xs font-semibold text-fg"
                >
                    البحث عن العميل
                </label>


                <div class="relative">

                    {{-- Search icon --}}
                    <i
                        class="fa-solid fa-magnifying-glass pointer-events-none absolute right-3 top-1/2 z-10 -translate-y-1/2 text-xs text-dim"
                    ></i>


                    <input
                        id="complaintClientSearch"
                        type="search"
                        class="form-input w-full pr-9 pl-10"
                        placeholder="ابحث باسم العميل أو الكود..."
                        autocomplete="off"
                        spellcheck="false"
                        aria-label="البحث عن العميل"
                    />


                    {{-- Clear search --}}
                    <button
                        type="button"
                        id="clearComplaintClientSearch"
                        class="absolute left-2 top-1/2 hidden h-7 w-7 -translate-y-1/2 items-center justify-center rounded-lg text-dim transition hover:bg-white/[0.05] hover:text-fg"
                        title="مسح البحث"
                        aria-label="مسح البحث"
                    >
                        <i class="fa-solid fa-xmark text-xs"></i>
                    </button>

                </div>


                {{-- Search result information --}}
                <div class="mt-2 flex items-center justify-between gap-2">

                    <span
                        id="complaintClientSearchHint"
                        class="text-[10px] text-dim"
                    >
                        اكتب اسم العميل أو الكود للبحث
                    </span>

                    <span
                        id="complaintClientResultCount"
                        class="hidden text-[10px] font-semibold text-info"
                    ></span>

                </div>


                {{-- ====================================================
                     SEARCH RESULTS
                     ==================================================== --}}

                <div
                    id="complaintClientResults"
                    class="mt-2 hidden max-h-64 overflow-y-auto rounded-xl border border-white/10 bg-[#111418] shadow-xl"
                >

                    {{-- Results are generated by JavaScript --}}

                </div>


                {{-- No results --}}
                <div
                    id="complaintClientNoResults"
                    class="mt-2 hidden rounded-xl border border-warning/20 bg-warning/[0.03] p-4 text-center"
                >

                    <div class="mx-auto flex h-9 w-9 items-center justify-center rounded-xl border border-warning/20 bg-warning/10 text-warning">
                        <i class="fa-solid fa-user-slash text-xs"></i>
                    </div>

                    <p class="mt-2 text-xs font-semibold text-fg">
                        لم يتم العثور على عميل
                    </p>

                    <p class="mt-1 text-[10px] text-dim">
                        جرّب البحث باستخدام جزء من الاسم أو كود العميل.
                    </p>

                </div>

            </div>


            {{-- ========================================================
                 ORIGINAL CUSTOMER SELECT
                 ======================================================== --}}

            <div class="mt-3">

                <x-select-field
                    name="client_code"
                    label="العميل المحدد"
                    :options="$clients"
                    placeholder="اختر العميل..."
                />

            </div>


            {{-- ========================================================
                 SELECTED CUSTOMER PREVIEW
                 ======================================================== --}}

            <div
                id="selectedComplaintClient"
                class="mt-3 hidden rounded-xl border border-brand/20 bg-brand/[0.04] p-3"
            >

                <div class="flex items-center justify-between gap-3">

                    <div class="flex min-w-0 items-center gap-3">

                        <div class="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl border border-brand/20 bg-brand/10 text-brand">
                            <i class="fa-solid fa-user-check text-xs"></i>
                        </div>

                        <div class="min-w-0">

                            <p class="text-[10px] text-dim">
                                العميل المحدد
                            </p>

                            <p
                                id="selectedComplaintClientName"
                                class="mt-0.5 truncate text-sm font-bold text-fg"
                            ></p>

                            <p
                                id="selectedComplaintClientCode"
                                class="mt-0.5 font-mono text-[10px] text-brand"
                            ></p>

                        </div>

                    </div>


                    <button
                        type="button"
                        id="changeComplaintClient"
                        class="btn btn-secondary btn-sm"
                    >
                        تغيير
                    </button>

                </div>

            </div>


            {{-- Customer keyboard hint --}}
            <div class="mt-3 flex flex-wrap items-center gap-2 text-[10px] text-dim">

                <span>
                    <i class="fa-solid fa-keyboard ml-1"></i>
                    البحث يدعم:
                </span>

                <span class="badge badge-neutral">
                    الاسم
                </span>

                <span class="badge badge-neutral font-mono">
                    ID / Code
                </span>

                <span class="badge badge-neutral">
                    جزء من الاسم
                </span>

            </div>

        </div>


        {{-- ============================================================
             COMPLAINT INFORMATION
             ============================================================ --}}

        <div class="rounded-xl border border-white/[0.06] bg-white/[0.015] p-4">

            <div class="mb-4 flex items-start gap-3">

                <div class="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl border border-warning/20 bg-warning/10 text-warning">
                    <i class="fa-solid fa-envelope-open-text text-sm"></i>
                </div>

                <div>

                    <h3 class="text-sm font-bold text-fg">
                        بيانات الشكوى
                    </h3>

                    <p class="mt-1 text-[10px] text-dim">
                        حدد الأولوية والمصدر ثم اكتب موضوع وتفاصيل الشكوى.
                    </p>

                </div>

            </div>


            {{-- Priority / source / employee --}}
            <div class="grid grid-cols-1 gap-3 md:grid-cols-2">

                <x-select-field
                    name="assigned_to"
                    label="إسناد إلى"
                    :options="$employees"
                    placeholder="بدون إسناد"
                />

                <x-select-field
                    name="priority"
                    label="الأولوية"
                    :options="$priorities"
                    value="medium"
                />

                <x-select-field
                    name="source"
                    label="مصدر الشكوى"
                    :options="$sources"
                    placeholder="اختر المصدر..."
                />

            </div>


            {{-- Subject --}}
            <div class="mt-3">

                <x-form-field
                    name="subject"
                    label="الموضوع"
                    placeholder="عنوان مختصر وواضح للشكوى"
                />

                <div class="mt-1 flex justify-end">

                    <span
                        id="complaintSubjectCounter"
                        class="text-[10px] text-dim"
                    >
                        0 حرف
                    </span>

                </div>

            </div>


            {{-- Description --}}
            <div class="mt-3">

                <x-textarea-field
                    name="description"
                    label="تفاصيل الشكوى"
                    rows="5"
                />

                <div class="mt-1 flex items-center justify-between gap-2">

                    <span class="text-[10px] text-dim">
                        اكتب تفاصيل المشكلة بوضوح لتسهيل المتابعة والمعالجة.
                    </span>

                    <span
                        id="complaintDescriptionCounter"
                        class="shrink-0 text-[10px] text-dim"
                    >
                        0 حرف
                    </span>

                </div>

            </div>

        </div>


        {{-- ============================================================
             SMART HELP
             ============================================================ --}}

        <div class="rounded-xl border border-info/20 bg-info/[0.035] p-3">

            <div class="flex items-start gap-2">

                <i class="fa-solid fa-circle-info mt-0.5 text-xs text-info"></i>

                <div class="min-w-0">

                    <p class="text-[11px] font-bold text-fg">
                        نصائح لتسجيل شكوى احترافية
                    </p>

                    <ul class="mt-1 space-y-1 text-[10px] leading-5 text-dim">

                        <li>
                            <i class="fa-solid fa-check ml-1 text-brand"></i>
                            استخدم عنواناً مختصراً يوضح المشكلة.
                        </li>

                        <li>
                            <i class="fa-solid fa-check ml-1 text-brand"></i>
                            اذكر التفاصيل المهمة التي يحتاجها المسؤول.
                        </li>

                        <li>
                            <i class="fa-solid fa-check ml-1 text-brand"></i>
                            اختر الأولوية المناسبة حسب أهمية الشكوى.
                        </li>

                        <li>
                            <i class="fa-solid fa-check ml-1 text-brand"></i>
                            إسناد الشكوى لموظف يساعد على ضمان المتابعة.
                        </li>

                    </ul>

                </div>

            </div>

        </div>


        {{-- ============================================================
             FORM ACTIONS
             ============================================================ --}}

        <div class="flex flex-wrap items-center justify-between gap-2">

            <div class="text-[10px] text-dim">

                <i class="fa-solid fa-shield-halved ml-1"></i>

                سيتم حفظ الشكوى داخل النظام.

            </div>


            <div class="flex gap-2">

                <button
                    type="submit"
                    id="createComplaintButton"
                    class="btn btn-primary"
                >
                    <i class="fa-solid fa-floppy-disk text-xs"></i>
                    تسجيل الشكوى
                </button>

                <button
                    type="button"
                    class="btn btn-secondary"
                    data-close-modal
                >
                    إلغاء
                </button>

            </div>

        </div>

    </form>

</x-modal>


@push('scripts')

<script>
document.addEventListener('DOMContentLoaded', function () {

    /*
    |--------------------------------------------------------------------------
    | Elements
    |--------------------------------------------------------------------------
    */

    const form = document.getElementById('newComplaintForm');

    if (!form) {
        return;
    }


    const searchInput =
        document.getElementById('complaintClientSearch');

    const clearSearchButton =
        document.getElementById('clearComplaintClientSearch');

    const resultsContainer =
        document.getElementById('complaintClientResults');

    const noResults =
        document.getElementById('complaintClientNoResults');

    const searchHint =
        document.getElementById('complaintClientSearchHint');

    const resultCount =
        document.getElementById('complaintClientResultCount');

    const selectedPreview =
        document.getElementById('selectedComplaintClient');

    const selectedName =
        document.getElementById('selectedComplaintClientName');

    const selectedCode =
        document.getElementById('selectedComplaintClientCode');

    const changeClientButton =
        document.getElementById('changeComplaintClient');

    const saveButton =
        document.getElementById('createComplaintButton');

    const subjectCounter =
        document.getElementById('complaintSubjectCounter');

    const descriptionCounter =
        document.getElementById('complaintDescriptionCounter');


    /*
    |--------------------------------------------------------------------------
    | Find the original client select
    |--------------------------------------------------------------------------
    */

    const clientSelect =
        form.querySelector('[name="client_code"]');


    /*
    |--------------------------------------------------------------------------
    | Read customers from the existing select
    |--------------------------------------------------------------------------
    |
    | This means we don't need a new endpoint or AJAX request.
    |
    | Each existing option becomes searchable by:
    |
    | 1. Option text
    | 2. Option value
    |
    */

    const customers = [];

    if (clientSelect) {

        Array.from(clientSelect.options).forEach(function (option) {

            /*
             * Ignore the placeholder.
             */

            if (!option.value) {
                return;
            }


            customers.push({
                value: option.value,
                label: option.textContent.trim(),
                search:
                    (
                        option.textContent +
                        ' ' +
                        option.value
                    ).toLowerCase()
            });

        });

    }


    /*
    |--------------------------------------------------------------------------
    | Selected customer
    |--------------------------------------------------------------------------
    */

    let selectedCustomer = null;


    /*
    |--------------------------------------------------------------------------
    | Normalize search
    |--------------------------------------------------------------------------
    */

    function normalize(value) {

        return String(value || '')
            .toLowerCase()
            .trim();

    }


    /*
    |--------------------------------------------------------------------------
    | Escape HTML
    |--------------------------------------------------------------------------
    */

    function escapeHtml(value) {

        return String(value || '')
            .replace(/&/g, '&amp;')
            .replace(/</g, '&lt;')
            .replace(/>/g, '&gt;')
            .replace(/"/g, '&quot;')
            .replace(/'/g, '&#039;');

    }


    /*
    |--------------------------------------------------------------------------
    | Render customer results
    |--------------------------------------------------------------------------
    */

    function renderCustomerResults(query) {

        if (!resultsContainer) {
            return;
        }


        const normalizedQuery = normalize(query);


        /*
         * Don't display all customers immediately.
         * This keeps the interface clean and fast.
         */

        if (!normalizedQuery) {

            resultsContainer.classList.add('hidden');

            resultsContainer.innerHTML = '';

            if (noResults) {
                noResults.classList.add('hidden');
            }

            if (resultCount) {
                resultCount.classList.add('hidden');
            }

            if (searchHint) {
                searchHint.textContent =
                    'اكتب اسم العميل أو الكود للبحث';
            }

            return;

        }


        /*
         * Search by name OR ID/code.
         */

        const matches = customers.filter(function (customer) {

            return customer.search.includes(normalizedQuery);

        });


        /*
         * Result count
         */

        if (resultCount) {

            resultCount.classList.remove('hidden');

            resultCount.textContent =
                new Intl.NumberFormat('ar-EG').format(matches.length) +
                ' نتيجة';

        }


        /*
         * No results
         */

        if (!matches.length) {

            resultsContainer.classList.add('hidden');

            resultsContainer.innerHTML = '';

            if (noResults) {
                noResults.classList.remove('hidden');
            }

            if (searchHint) {
                searchHint.textContent =
                    'لم يتم العثور على نتائج';
            }

            return;

        }


        if (noResults) {
            noResults.classList.add('hidden');
        }


        if (searchHint) {
            searchHint.textContent =
                'اختر العميل من النتائج';
        }


        /*
         * Maximum visible results.
         *
         * This prevents a huge DOM list if the database contains
         * thousands of customers.
         */

        const visibleMatches = matches.slice(0, 50);


        resultsContainer.innerHTML =
            visibleMatches.map(function (customer) {

                const safeValue =
                    escapeHtml(customer.value);

                const safeLabel =
                    escapeHtml(customer.label);


                return `
                    <button
                        type="button"
                        class="complaint-client-result flex w-full items-center justify-between gap-3 border-b border-white/[0.05] px-3 py-3 text-right transition last:border-b-0 hover:bg-white/[0.04]"
                        data-client-value="${safeValue}"
                    >

                        <div class="flex min-w-0 items-center gap-3">

                            <div class="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl border border-info/20 bg-info/10 text-info">
                                <i class="fa-solid fa-user text-xs"></i>
                            </div>

                            <div class="min-w-0">

                                <p class="truncate text-xs font-semibold text-fg">
                                    ${safeLabel}
                                </p>

                                <p class="mt-1 font-mono text-[10px] text-dim">
                                    ID / Code:
                                    ${safeValue}
                                </p>

                            </div>

                        </div>

                        <i class="fa-solid fa-chevron-left shrink-0 text-[9px] text-dim"></i>

                    </button>
                `;

            }).join('');


        resultsContainer.classList.remove('hidden');


        /*
         * If there are more than 50 results.
         */

        if (matches.length > 50) {

            resultsContainer.insertAdjacentHTML(
                'beforeend',
                `
                    <div class="border-t border-white/[0.05] px-3 py-2 text-center text-[10px] text-dim">
                        يتم عرض أول 50 نتيجة فقط، تابع الكتابة لتضييق البحث.
                    </div>
                `
            );

        }


        /*
         * Attach selection events.
         */

        resultsContainer
            .querySelectorAll('.complaint-client-result')
            .forEach(function (button) {

                button.addEventListener('click', function () {

                    selectCustomer(
                        this.dataset.clientValue
                    );

                });

            });

    }


    /*
    |--------------------------------------------------------------------------
    | Select customer
    |--------------------------------------------------------------------------
    */

    function selectCustomer(value) {

        const customer =
            customers.find(function (item) {

                return String(item.value) === String(value);

            });


        if (!customer) {
            return;
        }


        selectedCustomer = customer;


        /*
         * Update original backend select.
         */

        if (clientSelect) {

            clientSelect.value = customer.value;

            clientSelect.dispatchEvent(
                new Event('change', {
                    bubbles: true
                })
            );

        }


        /*
         * Update search input.
         */

        if (searchInput) {

            searchInput.value = customer.label;

        }


        /*
         * Hide results.
         */

        if (resultsContainer) {

            resultsContainer.classList.add('hidden');

            resultsContainer.innerHTML = '';

        }


        if (noResults) {
            noResults.classList.add('hidden');
        }


        if (resultCount) {

            resultCount.classList.remove('hidden');

            resultCount.textContent = 'تم الاختيار';

        }


        if (searchHint) {

            searchHint.textContent =
                'تم تحديد العميل بنجاح';

        }


        /*
         * Selected customer preview.
         */

        if (selectedPreview) {

            selectedPreview.classList.remove('hidden');

        }


        if (selectedName) {

            selectedName.textContent =
                customer.label;

        }


        if (selectedCode) {

            selectedCode.textContent =
                customer.value;

        }


        /*
         * Focus next logical field.
         */

        const assignedField =
            form.querySelector('[name="assigned_to"]');

        if (assignedField) {

            assignedField.focus();

        }

    }


    /*
    |--------------------------------------------------------------------------
    | Search input
    |--------------------------------------------------------------------------
    */

    if (searchInput) {

        searchInput.addEventListener('input', function () {

            const value = this.value;

            /*
             * Show clear button.
             */

            if (clearSearchButton) {

                if (value.trim() !== '') {

                    clearSearchButton.classList.remove('hidden');
                    clearSearchButton.classList.add('flex');

                } else {

                    clearSearchButton.classList.add('hidden');
                    clearSearchButton.classList.remove('flex');

                }

            }


            /*
             * If the user changes the search after selecting,
             * don't pretend the old customer is still selected.
             */

            if (
                selectedCustomer &&
                normalize(value) !==
                normalize(selectedCustomer.label)
            ) {

                selectedCustomer = null;

                if (selectedPreview) {
                    selectedPreview.classList.add('hidden');
                }

                if (clientSelect) {
                    clientSelect.value = '';
                }

            }


            renderCustomerResults(value);

        });


        /*
         * Focus opens search guidance.
         */

        searchInput.addEventListener('focus', function () {

            if (this.value.trim() !== '') {

                renderCustomerResults(this.value);

            }

        });


        /*
         * Keyboard navigation.
         */

        searchInput.addEventListener('keydown', function (event) {

            if (event.key === 'Escape') {

                if (resultsContainer) {
                    resultsContainer.classList.add('hidden');
                }

                return;

            }


            if (event.key === 'ArrowDown') {

                const firstResult =
                    resultsContainer
                        ? resultsContainer.querySelector(
                            '.complaint-client-result'
                        )
                        : null;

                if (firstResult) {

                    event.preventDefault();

                    firstResult.focus();

                }

            }

        });

    }


    /*
    |--------------------------------------------------------------------------
    | Clear customer search
    |--------------------------------------------------------------------------
    */

    if (clearSearchButton) {

        clearSearchButton.addEventListener('click', function () {

            if (searchInput) {

                searchInput.value = '';

                searchInput.focus();

            }


            if (clientSelect) {
                clientSelect.value = '';
            }


            selectedCustomer = null;


            if (selectedPreview) {
                selectedPreview.classList.add('hidden');
            }


            if (resultsContainer) {

                resultsContainer.classList.add('hidden');

                resultsContainer.innerHTML = '';

            }


            if (noResults) {
                noResults.classList.add('hidden');
            }


            if (resultCount) {
                resultCount.classList.add('hidden');
            }


            if (searchHint) {

                searchHint.textContent =
                    'اكتب اسم العميل أو الكود للبحث';

            }

        });

    }


    /*
    |--------------------------------------------------------------------------
    | Change customer
    |--------------------------------------------------------------------------
    */

    if (changeClientButton) {

        changeClientButton.addEventListener('click', function () {

            selectedCustomer = null;


            if (selectedPreview) {
                selectedPreview.classList.add('hidden');
            }


            if (clientSelect) {
                clientSelect.value = '';
            }


            if (searchInput) {

                searchInput.value = '';

                searchInput.focus();

            }


            if (resultCount) {
                resultCount.classList.add('hidden');
            }


            if (searchHint) {

                searchHint.textContent =
                    'اكتب اسم العميل أو الكود للبحث';

            }

        });

    }


    /*
    |--------------------------------------------------------------------------
    | Keep search synchronized with original select
    |--------------------------------------------------------------------------
    */

    if (clientSelect) {

        clientSelect.addEventListener('change', function () {

            if (!this.value) {

                selectedCustomer = null;

                if (selectedPreview) {
                    selectedPreview.classList.add('hidden');
                }

                return;

            }


            const customer =
                customers.find(function (item) {

                    return String(item.value) ===
                        String(clientSelect.value);

                });


            if (customer) {

                selectedCustomer = customer;


                if (searchInput) {
                    searchInput.value = customer.label;
                }


                if (selectedPreview) {
                    selectedPreview.classList.remove('hidden');
                }


                if (selectedName) {
                    selectedName.textContent = customer.label;
                }


                if (selectedCode) {
                    selectedCode.textContent = customer.value;
                }

            }

        });

    }


    /*
    |--------------------------------------------------------------------------
    | Character counters
    |--------------------------------------------------------------------------
    */

    const subjectField =
        form.querySelector('[name="subject"]');

    const descriptionField =
        form.querySelector('[name="description"]');


    function updateSubjectCounter() {

        if (!subjectField || !subjectCounter) {
            return;
        }


        const length =
            subjectField.value.length;


        subjectCounter.textContent =
            new Intl.NumberFormat('ar-EG').format(length) +
            ' حرف';

    }


    function updateDescriptionCounter() {

        if (!descriptionField || !descriptionCounter) {
            return;
        }


        const length =
            descriptionField.value.length;


        descriptionCounter.textContent =
            new Intl.NumberFormat('ar-EG').format(length) +
            ' حرف';

    }


    if (subjectField) {

        subjectField.addEventListener(
            'input',
            updateSubjectCounter
        );

    }


    if (descriptionField) {

        descriptionField.addEventListener(
            'input',
            updateDescriptionCounter
        );

    }


    updateSubjectCounter();
    updateDescriptionCounter();


    /*
    |--------------------------------------------------------------------------
    | Form submit protection
    |--------------------------------------------------------------------------
    */

    let submitting = false;


    if (form) {

        form.addEventListener('submit', function (event) {

            /*
             * Don't allow duplicate submissions.
             */

            if (submitting) {

                event.preventDefault();

                return;

            }


            /*
             * Customer is required.
             */

            if (
                clientSelect &&
                !clientSelect.value
            ) {

                event.preventDefault();

                if (searchInput) {

                    searchInput.focus();

                }

                if (searchHint) {

                    searchHint.textContent =
                        'يجب اختيار العميل أولاً';

                    searchHint.classList.add('text-danger');

                    setTimeout(function () {

                        searchHint.classList.remove(
                            'text-danger'
                        );

                    }, 2000);

                }

                return;

            }


            /*
             * Subject.
             */

            if (
                subjectField &&
                subjectField.value.trim() === ''
            ) {

                event.preventDefault();

                subjectField.focus();

                return;

            }


            /*
             * Description.
             */

            if (
                descriptionField &&
                descriptionField.value.trim() === ''
            ) {

                event.preventDefault();

                descriptionField.focus();

                return;

            }


            /*
             * Submit.
             */

            submitting = true;


            if (saveButton) {

                saveButton.disabled = true;

                saveButton.classList.add(
                    'opacity-70',
                    'cursor-not-allowed'
                );

                saveButton.innerHTML =
                    '<i class="fa-solid fa-spinner fa-spin text-xs"></i>' +
                    ' جاري تسجيل الشكوى...';

            }

        });

    }


    /*
    |--------------------------------------------------------------------------
    | Reset helper
    |--------------------------------------------------------------------------
    */

    function resetComplaintFormState() {

        selectedCustomer = null;


        if (searchInput) {

            searchInput.value = '';

        }


        if (clientSelect) {

            clientSelect.value = '';

        }


        if (resultsContainer) {

            resultsContainer.classList.add('hidden');

            resultsContainer.innerHTML = '';

        }


        if (noResults) {
            noResults.classList.add('hidden');
        }


        if (selectedPreview) {
            selectedPreview.classList.add('hidden');
        }


        if (resultCount) {
            resultCount.classList.add('hidden');
        }


        if (clearSearchButton) {

            clearSearchButton.classList.add('hidden');
            clearSearchButton.classList.remove('flex');

        }


        if (searchHint) {

            searchHint.textContent =
                'اكتب اسم العميل أو الكود للبحث';

        }

    }


    /*
    |--------------------------------------------------------------------------
    | Close modal reset
    |--------------------------------------------------------------------------
    */

    document.addEventListener('click', function (event) {

        const closeButton =
            event.target.closest('[data-close-modal]');


        if (!closeButton) {
            return;
        }


        /*
         * Give the modal system time to close first.
         */

        setTimeout(function () {

            resetComplaintFormState();

        }, 100);

    });


    /*
    |--------------------------------------------------------------------------
    | Click outside results
    |--------------------------------------------------------------------------
    */

    document.addEventListener('click', function (event) {

        if (!resultsContainer || !searchInput) {
            return;
        }


        if (
            event.target.closest('#complaintClientSearch') ||
            event.target.closest('#complaintClientResults')
        ) {

            return;

        }


        resultsContainer.classList.add('hidden');

    });

});
</script>

@endpush