<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

// ---------------------------------------------------------------------
// CLIENTS  =  the PERSON (the debtor). One person = one row, even if he owes money
// to several banks. The debt itself lives in debt_cases (migration 16).
// Used by: clients table, edit modal (personal data + work data).
// Phones are in client_phones (next migration).
// ---------------------------------------------------------------------
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('clients', function (Blueprint $table) {
            $table->id();

            $table->string('code', 20)->unique();         // "كود العميل" (1000001). Generated by the app, starts at 1000000
            $table->string('national_id', 14)->unique();  // Egyptian national ID = exactly 14 digits; also prevents duplicate clients on import
            $table->string('name');                       // full name
            $table->string('email')->nullable();

            // address
            $table->foreignId('governorate_id')->nullable()->constrained()->nullOnDelete(); // "المحافظة"
            $table->string('address', 500)->nullable();   // "العنوان بالتفصيل"

            // work data (modal card "بيانات العمل")
            $table->string('employer_name')->nullable();  // "جهة العمل"
            $table->string('job_title')->nullable();      // "المسمى الوظيفي"
            $table->string('work_address', 500)->nullable(); // "عنوان العمل" (work phone is in client_phones, label = work)

            $table->text('notes')->nullable();            // internal notes about the client

            $table->timestamps();
            $table->softDeletes();

            $table->index('name');                        // speeds up search by name
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('clients');
    }
};
